ALTER TABLE LCO_WITHHOLDINGRULECONF ADD COLUMN ISUSEPRODUCTTAXCATEGORY CHAR(1) 
	DEFAULT 'N' NOT NULL CHECK (isuseproducttaxcategory IN ('Y',
	'N'))
;

alter table LCO_WITHHOLDINGRULE add column   C_TAXCATEGORY_ID  NUMERIC(10)
;

alter table LCO_WITHHOLDINGRULE add   CONSTRAINT TAXCATEGORY_WITHHOLDING 
 FOREIGN KEY (C_TAXCATEGORY_ID) 
 REFERENCES C_TAXCATEGORY (C_TAXCATEGORY_ID)
;